### ISSUE TITLE
Minor UTM code format change for next version (not urgent)

### ISSUE THREAD

**Issue by Barn2** [Barn2Media/woo-custom-add-to-cart-button#1]
We are making the format of our UTM codes more consistent over time. In the next version (no need to do a release just for this), please could you change the UTM codes on the WooCommerce Custom Add to Cart Button wordpress.org page in the readme to: /?utm_source=wporg&utm_medium=freeplugin&utm_campaign=freepluginwporg&utm_content=atoc-free

This adds the 'medium' and 'campaign' parameters to the UTM code, which are currently missing.

**Comment by LuigiPulcini** [comment]
In addition to updating the compatibility with the latest WP and WC version, all the links in the readme file have just been updated as per this request.
